spring.application.name=lager-ordersystem
spring.datasource.url=jdbc:postgresql://localhost:5432/lagerdb
spring.datasource.username=jan
spring.datasource.password=jan123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true